### ISSUE TITLE
Move resources to a dedicated directory

### ISSUE THREAD

**Issue by atyachari** [atyachari/Flippy#13]
Move resources like images and configs to a dedicated directory

**Comment by jotasprout** [comment]
Please assign this to me.

**Comment by jotasprout** [comment]
Thank you! I am on the case! Will get to it after work this afternoon.

**Comment by jotasprout** [comment]
Sorry, first day of new job was super long and I haven't started yet but am still committed.

**Comment by atyachari** [comment]
@jotasprout Added a comment in PR

**Comment by atyachari** [comment]
Resolved in #32 
Thanks for the contribution @jotasprout

**Comment by atyachari** [comment]
@jotasprout can you also update the game.py file, so that images and config are referred correctly
