### ISSUE TITLE
Move static variables to a different config file

### ISSUE THREAD

**Issue by atyachari** [atyachari/Flippy#6]
Move the static variables in game.py to a config file

**Comment by PentW0lf** [comment]
you want to remove all static variable to another py file and import it right?

**Comment by daweedkob** [comment]
!assign

**Comment by atyachari** [comment]
yes, that is correct @PentW0lf

**Comment by daweedkob** [comment]
Assign me to the issue

**Comment by atyachari** [comment]
one correction, the config file shouldn't be a py file, it should be .ini

**Comment by PentW0lf** [comment]
okay i would like to do it and what will be the name of the file? and assign me.

**Comment by proffapt** [comment]
@atyachari solved in #8

**Comment by proffapt** [comment]
will not be applicable for hacktoberfest .. see #9

**Comment by PentW0lf** [comment]
Hey, can you review it, it's done @atyachari

**Comment by PentW0lf** [comment]
Hey @atyachari, Pls review it, It's done !

**Comment by atyachari** [comment]
@proffapt can you take some other task. This one is already assigned.

**Comment by proffapt** [comment]
@atyachari can you look at the issue #8 again?

**Comment by proffapt** [comment]
Maybe try reading hacktoberfest manual in how to participate :)

**Comment by PentW0lf** [comment]
@atyachari i have done issue,pls check #10

**Comment by atyachari** [comment]
Thanks for the contribution @PentW0lf
