### ISSUE TITLE
Reduce the cognitive complexity of runGame method

### ISSUE THREAD

**Issue by atyachari** [atyachari/Flippy#7]
Modularize the runGame method in game.py into smaller methods

**Comment by proffapt** [comment]
will not be applicable for hacktoberfest .. see #9

**Comment by atyachari** [comment]
added all necessary tags

**Comment by Adarsh-sophos** [comment]
@atyachari resolved in #24 
Please review!

**Comment by atyachari** [comment]
Awesome!! Thanks @Adarsh-sophos
