### ISSUE TITLE
Add `hacktoberfest` label to this repository

### ISSUE THREAD

**Issue by proffapt** [atyachari/Flippy#9]
In order to make this repository eligible in hacktoberfest, you need to add a label "hacktoberfest" to this repository.

<img width="382" alt="image" src="https://user-images.githubusercontent.com/86282911/194031034-57bbf3db-a2c5-468c-9391-85ed408c0f53.png">
You just have to click on that gear icon and then type 'hacktoberfest' in the Topics the choose ok/apply/done.

**Comment by proffapt** [comment]
check out the tags in this repository..

https://github.com/proffapt/code-runner

**Comment by atyachari** [comment]
Labels are only applied in PRs or issues

**Comment by proffapt** [comment]
My bad, it's not called label.. it's called tag..
